"""add idms_month_end and charge off recovery_acv

Revision ID: b1da0cd3226f
Revises: c47db103ab76
Create Date: 2026-08-28 19:23:14.856202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1da0cd3226f'
down_revision: Union[str, Sequence[str], None] = 'c47db103ab76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idms_month_end',
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('acct_id', sa.String(length=50), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=True),
    sa.Column('borrower', sa.String(length=200), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('cur_prin_bal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cur_prin_bal_plus_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cur_int_bal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cur_sales_tax_bal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cur_non_earning_prin_bal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cur_note_bal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('payment_recency', sa.Integer(), nullable=True),
    sa.Column('acct_status', sa.String(length=20), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_idms_month_end_acct', 'idms_month_end', ['acct_id'], unique=False)
    op.create_index('ix_idms_month_end_period', 'idms_month_end', ['period_year', 'period_month'], unique=False)
    # server_default para poder agregarla NOT NULL sobre las filas ya cargadas.
    op.add_column(
        'idms_charge_offs',
        sa.Column(
            'recovery_acv',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('idms_charge_offs', 'recovery_acv')
    op.drop_index('ix_idms_month_end_period', table_name='idms_month_end')
    op.drop_index('ix_idms_month_end_acct', table_name='idms_month_end')
    op.drop_table('idms_month_end')
