"""initial tables

Revision ID: b3125e7d2623
Revises: 
Create Date: 2026-04-29 13:41:09.494456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3125e7d2623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('total_cars', sa.Integer(), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ticket_average', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_of_goods', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cogs_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_profit_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_daily_sales_date', 'daily_sales', ['date'], unique=False)
    op.create_table('hours_summary',
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('labor_dollars', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_sold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hours_paid', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('advisor_efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technician_proficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technician_productivity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technician_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('technician_hours',
    sa.Column('technician_name', sa.String(length=100), nullable=False),
    sa.Column('labor_dollars', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_sold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hours_paid', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('technician_proficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technician_productivity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_technician_hours_name_period', 'technician_hours', ['technician_name', 'period_start'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('work_in_progress',
    sa.Column('shop_number', sa.Integer(), nullable=False),
    sa.Column('ro_number', sa.String(length=20), nullable=False),
    sa.Column('op_code', sa.String(length=50), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('advisor', sa.String(length=50), nullable=True),
    sa.Column('opened', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days_open', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=150), nullable=False),
    sa.Column('stock_other_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle', sa.String(length=150), nullable=False),
    sa.Column('vin', sa.String(length=20), nullable=False),
    sa.Column('estimated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cog', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('col', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_in_progress')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_technician_hours_name_period', table_name='technician_hours')
    op.drop_table('technician_hours')
    op.drop_table('hours_summary')
    op.drop_index('ix_daily_sales_date', table_name='daily_sales')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
