"""add idms charge offs table

Revision ID: c47db103ab76
Revises: b4c5d6e7f8a9
Create Date: 2026-08-26 14:43:28.746091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47db103ab76'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idms_charge_offs',
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('acct_id', sa.String(length=50), nullable=False),
    sa.Column('borrower', sa.String(length=200), nullable=True),
    sa.Column('date_sold', sa.Date(), nullable=True),
    sa.Column('charge_off_date', sa.Date(), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('original_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_total_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_adjusted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repo_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('acct_flags', sa.String(length=200), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_idms_charge_off_acct', 'idms_charge_offs', ['acct_id'], unique=False)
    op.create_index('ix_idms_charge_off_co_date', 'idms_charge_offs', ['charge_off_date'], unique=False)
    op.create_index('ix_idms_charge_off_year', 'idms_charge_offs', ['report_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idms_charge_off_year', table_name='idms_charge_offs')
    op.drop_index('ix_idms_charge_off_co_date', table_name='idms_charge_offs')
    op.drop_index('ix_idms_charge_off_acct', table_name='idms_charge_offs')
    op.drop_table('idms_charge_offs')
    # ### end Alembic commands ###
